"""initial_schema

Revision ID: d584390723bb
Revises: 
Create Date: 2026-03-13 16:46:45.118191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd584390723bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffer_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relation_type_id'], ['relation_types.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_tags',
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    # ### end Alembic commands ###

    dialect = op.get_bind().dialect.name

    if dialect == "sqlite":
        # FTS5 virtual table + triggers (SQLite full-text search)
        op.execute(
            "CREATE VIRTUAL TABLE IF NOT EXISTS notes_fts "
            "USING fts5(note_id UNINDEXED, title, content)"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS notes_fts_ai "
            "AFTER INSERT ON notes BEGIN "
            "  INSERT INTO notes_fts(note_id, title, content) "
            "  VALUES (new.id, new.title, new.content); "
            "END"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS notes_fts_au "
            "AFTER UPDATE ON notes BEGIN "
            "  DELETE FROM notes_fts WHERE note_id = old.id; "
            "  INSERT INTO notes_fts(note_id, title, content) "
            "  VALUES (new.id, new.title, new.content); "
            "END"
        )
        op.execute(
            "CREATE TRIGGER IF NOT EXISTS notes_fts_ad "
            "AFTER DELETE ON notes BEGIN "
            "  DELETE FROM notes_fts WHERE note_id = old.id; "
            "END"
        )

    elif dialect == "postgresql":
        # tsvector column + GIN index + trigger (PostgreSQL full-text search)
        op.execute("ALTER TABLE notes ADD COLUMN search_vector tsvector")
        op.execute(
            "CREATE INDEX notes_search_vector_idx ON notes USING GIN(search_vector)"
        )
        op.execute("""
            CREATE OR REPLACE FUNCTION notes_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := to_tsvector('english',
                    COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.content, ''));
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER notes_fts_ai
            BEFORE INSERT OR UPDATE ON notes
            FOR EACH ROW EXECUTE FUNCTION notes_search_vector_update()
        """)


def downgrade() -> None:
    """Downgrade schema."""
    dialect = op.get_bind().dialect.name

    if dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS notes_fts_ad")
        op.execute("DROP TRIGGER IF EXISTS notes_fts_au")
        op.execute("DROP TRIGGER IF EXISTS notes_fts_ai")
        op.execute("DROP TABLE IF EXISTS notes_fts")
    elif dialect == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS notes_fts_ai ON notes")
        op.execute("DROP FUNCTION IF EXISTS notes_search_vector_update()")
        op.execute("DROP INDEX IF EXISTS notes_search_vector_idx")
        op.execute("ALTER TABLE notes DROP COLUMN IF EXISTS search_vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_tags')
    op.drop_table('links')
    op.drop_table('tags')
    op.drop_table('relation_types')
    op.drop_table('notes')
    op.drop_table('metadata')
    op.drop_table('buffer_notes')
    # ### end Alembic commands ###
